name: Upload HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload index.html artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-output
        path: index.html
