name: Upload HTML Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload HTML project
      uses: actions/upload-artifact@v4
      with:
        name: html-project
        path: |
          index.html
          style.css
          src/script.js
          resources/logo.png
          indexd.html
          dev.htmm
